# Site settings
title: Pierce的技术博客
email: 442130741@qq.com
description: > #Pierce-lph的技术博客
url: "https://lipeihan.github.io"
github_username:  lipeihan

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 黎培瀚
  email: 442130741@qq.com
  link: https://lipeihan.github.io
  github: http://github.com/lipeihan
title: Pierce的技术博客

# avatar头像及Favicon
avatar: https://avatars1.githubusercontent.com/u/5010799?v=3&amp;s=460
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:

# disqus 设置
disqus:
  shortname: lipeihan
